#+TITLE: 1.4 - Network Security

* 1.4.1 - Threats to computer systems and networks
** Forms of Attack
Network *Attacks* Come in different forms.
For example:
+ *Passive Attacks*, where someone monitors data that travels across a network and intercepts data packets on the chance that it may contain sensitive information.
  - They may use /network-monitoring/ hardware and software such as /packet sniffers/.
  - This makes them /hard to detect/ as the hacker is quietly listening. The best defence is *data encryption*
+ *Active Attacks*, where someone attacks a network with [[Malware][Malware]] or other planned attacks.
  - These are more easily detected, and the main defence is a *firewall*
+ <<Insider Attacks>> *Insider Attacks*, where someone within an organisation exploits their access to steal information.
+ *Brute Force Attacks*, where an attacker /actively/ tries to gain information by cracking security through /trial and error/.
  - They use automated software to produce hundreds of likely combinations on the chance that one is correct.
  - The best defence for these attacks are simple measures such as *locking accounts after too many failed attempts* and *stronger passwords*
+ *Denial of Service (DoS) Attacks*, where a hacker tries to prevent users from accessing a network or website by flooding it with useless traffic, making it *extremely slow or inaccessible*.
** Malware
1. *Malware (Malicious Software)* is installed on someones device, typically without their permission.
2. Typical actions that malware take include:
   a. *Deleting* or modifying files
   b. *Sacreware*, where the user is scared into paying the malware creators for the computer to be uninfected.
   c. *Locking Files*, such as /ransomware/
   d. *Spyware*
   e. *Rootkits*, which /alter user permissions/ and give hackers administrator access.
   f. Opening *Back-doors*, or holes in someones security.
3. Malware can *access* your device in different ways
   a. *Viruses* attach themselves to certain files, such as programs, so that when the file is run, they are activated.
   b. *Worms* are like viruses, but *self-replicate*, meaning that they can spread very quickly.
   c. *Trojans* are malware *designed as legitimate software*. They do not replicate themselves, instead relying on *unsuspecting users to install them*.
** Social engineering
Social engineering is the way of *gaining sensitive information by influencing people*. A common form relies on a *telephone scam call*, where people *pretend to be an administrator*, and persuade people to *disclose personal information*, such as /login details/.
Another type is *Phishing*, where *scam emails or texts* are sent, claiming to be from *a reputable company*, attempting to trick people into *disclosing sensitive info*, such as /bank details/. They are often *sent to thousands* of people, in the hope that someone will fall prey. To combat this, many email programs have *anti-phishing* features.
** SQL injection
Networks make use of databases, which are queried using *SQL*. *Injections* are *pieces of SQL* typed into a *website's input box*, causing a *malicious SQL query* to be carried out, such as all login information being outputted. If a websites SQL code is *insecure*, it can be *an easy way* for hackers to get past a firewall.
* 1.4.2 - Identifying and preventing vulnerabilities.
Common prevention methods include:
+ *Penetration Testing*, where *specialists simulate attacks* on a network to *identify weaknesses* before they are exploited.
+ *Physical Security*, where the *physical elements of a network are protected* from damage, both intentional and unintentional. This can be done through *Locks, pass codes and surveillance*
+ *Passwords*, to prevent *unauthorised users* gaining access.
+ *User access levels*, to *limit the number of people with access* to sensitive information, preventing [[Insider Attacks][Insider Attacks]] on the network.
+ *Anti-malware software*, to *find and stop malware* from damaging a network and its devices.
+ *Firewalls*, to *block unauthorised devices* from gaining access.
+ *Encryption*, to *protect data* travelling *over a network* securely.
